AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  DemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs10.x
      Handler: index.handler
      # CodeUri:
      #   Bucket: pk-demo-lambda
      #   Key: demo-lambda.zip
      CodeUri: ./src
      Events:
        # EveryMinute:
        #   Type: Schedule
        #   Properties:
        #     Schedule: rate(1 minute)
        # S3Upload:
        #   Type: S3
        #   Properties:
        #     Bucket: !Ref MyS3Bucket
        #     Events: s3:ObjectCreated:*
        OnApiCall:
          Type: Api
          Properties:
            Path: /demo-resource
            Method: Get
  # MyS3Bucket:
  #   Type: "AWS::S3::Bucket"
  #   Properties:
  #     BucketName: pk-file-uploads-bucket